baseURL = "/"
theme = "casper-two"
languageCode = "en-us"
title = "Justin J Stark"
disqusShortname = ""
paginate = 5

[params]
  title       = "Justin J Stark"
  subtitle    = "Software Developer"
  cover       = ""
  description = "Here is a description of your site."
  metaDescription = "Software Developer in Lincoln, NE"
  googleAnalytics = ""
  customCSS = []
  RSSLink = "https://justinjstark.com/post/index.xml"

  twitterName = "justinjstark"
  #fbName = ""
  githubName = "justinjstark"

  logo = "hugo-logo.png"
  #orgName = "EM"
  #orgWebsite = "https://www.telematika.org"
  #orgDescription = "Here is a description placeholder for your org"

  author = "Justin J Stark"
  authorAvatar = "img/JustinStark-Small.png"
  authorLocation = "Lincoln, NE"
  authorWebsite = "https://justinjstark.com"
  authorDescription = "Software Developer in Lincoln, NE"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "About"
  url = "/page/about"
  weight = 100
